Leave_requests/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('User_leave_requests/', views.User_leave_requests, name="User_leave_requests"),
    path('Manager_leave_requests/', views.Manager_leave_requests, name="Manager_leave_requests"),
    path('Manager_leave_requests/<int:user_id>/', views.Manager_leave_requests, name="Manager_leave_requests"),
    path('accept-leave-request/<uuid:request_id>/', views.accept_leave_request, name='accept_leave_request'),
    path('decline-leave-request/<uuid:request_id>/', views.decline_leave_request, name='decline_leave_request'),
    path('search-users/', views.search_users, name='search-users'),
]

Users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('logout/', views.logout_user, name="logout"),
    path('', views.login_user, name="login"),

    path('edit_account/', views.edit_account, name="edit_account"),
    path('add_employee/', views.add_employee, name="add_employee")
]

WorkWatch/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Users.urls')),
    path('', include('Leave_requests.urls')),
    path('', include('schedules.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.FILTERS_URL, document_root=settings.FILTERS_ROOT)

Leave_requests/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Leave_request(models.Model):
    STATUS_CHOICES = [
        ('1', 'oczekiwanie na rozpatrzenie'),
        ('2', 'zaakceptowany'),
        ('3', 'odrzucony'),
    ]

    LEAVE_TYPE_CHOICES = [
        ('1', 'urlop wypoczynkowy'),
        ('2', 'urlop na żądanie'),
        ('3', 'urlop opiekuńczy'),
        ('4', 'urlop z powodu siły wyższej'),
    ]

    request_id = models.UUIDField(default = uuid.uuid4, unique=True, primary_key=True, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='1')
    leave_type = models.CharField(max_length=1, choices=LEAVE_TYPE_CHOICES, default='1')
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField()

    def __str__(self) -> str:
        return str(self.user)

Leave_requests/forms.py
from django import forms
from .models import Leave_request

class LeaveRequestForm(forms.ModelForm):
    class Meta:
        model = Leave_request
        fields = ['start_date', 'end_date', 'leave_type']
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
        }
        labels = {
            'start_date': 'Data początkowa:', 
            'end_date': 'Data końcowa:', 
            'leave_type': 'Rodzaj urlopu:',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'input'})

Leave_requests/views.py
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.db.models import Q
from WorkWatch.decorators import non_manager_required, manager_required
from schedules.models import ScheduleDay
from .models import Leave_request
from .forms import LeaveRequestForm

@non_manager_required(login_url='login')
def User_leave_requests(request):
    user = request.user
    profile = user.profile
    form = LeaveRequestForm()
    requests_history = Leave_request.objects.filter(user=user).order_by('-start_date')

    if request.method == 'POST':
        form = LeaveRequestForm(request.POST)
        if form.is_valid():
            leave_request = form.save(commit=False)
            leave_request.user = user

            # Pobranie danych z formularza
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            leave_type = form.cleaned_data['leave_type']
            num_days_requested = (end_date - start_date).days + 1

            # Sprawdzanie dostępności dni urlopowych
            if leave_type == '1':  # Urlop wypoczynkowy
                if profile.available_leave >= num_days_requested:
                    profile.available_leave -= num_days_requested
                    if profile.available_leave < profile.on_demand_leave:
                        profile.on_demand_leave = profile.available_leave # Zaakceptowany, jeśli to urlop na żądanie
                else:
                    messages.error(request, 'Nie masz wystarczającej liczby dni urlopu wypoczynkowego.')
                    return redirect('User_leave_requests')
            elif leave_type == '2':  # Urlop na żądanie
                if profile.available_leave >= num_days_requested and profile.on_demand_leave >= num_days_requested:
                    profile.available_leave -= num_days_requested
                    profile.on_demand_leave -= num_days_requested
                    leave_request.status = '2'  # Od razu zaakceptowany
                else:
                    messages.error(request, 'Nie masz wystarczającej liczby dni urlopu na żądanie.')
                    return redirect('User_leave_requests')
            elif leave_type == '3':  # Urlop na żądanie
                if profile.parental_leave >= num_days_requested:
                    profile.parental_leave -= num_days_requested
                else:
                    messages.error(request, 'Nie masz wystarczającej liczby dni urlopu opiekuńczego.')
                    return redirect('User_leave_requests')
            elif leave_type == '4':  # Urlop na żądanie
                if profile.force_majeure_leave >= num_days_requested:
                    profile.force_majeure_leave -= num_days_requested
                else:
                    messages.error(request, 'Nie masz wystarczającej liczby dni urlopu z powodu siły wyższej.')
                    return redirect('User_leave_requests')    

            profile.save()
            leave_request.num_of_days = num_days_requested
            leave_request.save()
            messages.success(request, 'Wniosek urlopowy został złożony.')
            requests_history = Leave_request.objects.filter(user=user).order_by('-start_date')
            return redirect('User_leave_requests')

    context = {
        'form': form,
        'user': user,
        'profile': profile,
        'requests_history': requests_history,
    }
    return render(request, 'Leave_requests/user_leave_requests.html', context)

@manager_required(login_url='login')
def Manager_leave_requests(request, user_id=None):
    non_managers = User.objects.exclude(groups__name='Managers')

    users_with_pending_requests = non_managers.filter(
        leave_request__status='1'
    ).order_by('last_name', 'first_name').distinct()

    users_without_requests = non_managers.exclude(
        leave_request__status='1'
    ).order_by('last_name', 'first_name').distinct()

    selected_user = None
    profile = None
    requests_history = None
    pending_requests = None

    if user_id:
        selected_user = get_object_or_404(User, pk=user_id)
    elif users_with_pending_requests.exists():
        selected_user = users_with_pending_requests.first()
    elif users_without_requests.exists():
        selected_user = users_without_requests.first()

    if selected_user:
        profile = selected_user.profile
        requests_history = Leave_request.objects.filter(
            user=selected_user, 
            status__in=['2', '3']
        ).order_by('-start_date')
        pending_requests = Leave_request.objects.filter(
            user=selected_user, 
            status='1'
        ).order_by('start_date')

    context = {
        'users_with_pending_requests': users_with_pending_requests,
        'users_without_requests': users_without_requests,
        'profile': profile,
        'requests_history': requests_history,
        'pending_requests': pending_requests,
    }
    return render(request, 'Leave_requests/manager_leave_requests.html', context)

@manager_required(login_url='login')
def accept_leave_request(request, request_id):
    leave_request = get_object_or_404(Leave_request, pk=request_id)
    leave_request.status = '2'  # Status 'zaakceptowany'
    leave_request.save()

    # Pobierz id użytkownika wnioskującego o urlop
    user_id = leave_request.user.id

    # Usuń wszystkie ScheduleDay dla tego użytkownika, które zawierają się w zakresie dat wniosku urlopowego
    ScheduleDay.objects.filter(
        Q(schedule__user_id=user_id) &
        Q(start_time__gte=leave_request.start_date) &
        Q(end_time__lte=leave_request.end_date)
    ).delete()

    messages.success(request, 'Wniosek urlopowy został zaakceptowany.')
    return redirect('Manager_leave_requests', user_id=user_id)

@manager_required(login_url='login')
def decline_leave_request(request, request_id):
    leave_request = get_object_or_404(Leave_request, pk=request_id)
    leave_request.status = '3'  # Status 'odrzucony'
    leave_request.save()
    user_id = leave_request.user.id
    messages.error(request, 'Wniosek urlopowy został odrzucony.')
    return redirect('Manager_leave_requests', user_id=user_id)

def search_users(request):
    query = request.GET.get('query', '')
    non_managers = User.objects.exclude(groups__name='Managers')

    if query:
        results = non_managers.filter(
            Q(first_name__icontains=query) | Q(last_name__icontains=query)
        )
    else:
        results = non_managers

    # Logika do segregowania użytkowników z wnioskami i bez
    users_with_requests = results.filter(leave_request__status='1').distinct()
    users_without_requests = results.exclude(leave_request__status='1').distinct()

    data = []
    # Najpierw dodajemy użytkowników z wnioskami
    for user in users_with_requests:
        data.append(get_user_data(user, has_request=True))
    
    # Następnie resztę użytkowników
    for user in users_without_requests:
        data.append(get_user_data(user, has_request=False))

    return JsonResponse(data, safe=False)

def get_user_data(user, has_request=False):
    profile = user.profile if hasattr(user, 'profile') else None
    imageURL = profile.imageURL if profile else ''
    return {
        'first_name': user.first_name,
        'last_name': user.last_name,
        'username': user.username,
        'imageURL': imageURL,
        'id': user.id,
        'has_request': has_request  # Dodatkowe pole informujące o wniosku
    }

Leave_requests/templates/Leave_requests/manager_leave_requests.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="settingsPage profile my-xl">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="search-container">
            <input class="search__bar" type="text" id="search-box" placeholder="Szukaj pracownika...">
          </div>
          <div class="card__body dev" style="max-height:70rem; overflow-y: auto;">
            

            {% for user in users_with_pending_requests %}
            <div class="userCard">
              <img style="margin: 0rem; z-index: 111; background-color: white;" class="avatar avatar--md dev__avatar" src="{{ user.profile.imageURL }}" alt="Profile_logo"/>
              <a href="{% url 'Manager_leave_requests' user.id %}" style="width: -webkit-fill-available;">
                <div div style="background-color:#FFCF87;" class="userCard__text">
                  <p style="color:black;"><b>{{ user.first_name }} {{ user.last_name }}</b></p>
                  <p style="color:black;">{{ user.username }}</p>
                </div>
              </a>
            </div>
            {% endfor %}

            {% for user in users_without_requests %}
            <div class="userCard">
              <img style="margin: 0rem; z-index: 111; background-color: white;" class="avatar avatar--md dev__avatar" src="{{ user.profile.imageURL }}" alt="Profile_logo"/>
              <a href="{% url 'Manager_leave_requests' user.id %}" style="width: -webkit-fill-available;">
                <div class="userCard__text">
                  <p style="color:black;"><b>{{ user.first_name }} {{ user.last_name }}</b></p>
                  <p style="color:black;">{{ user.username }}</p>
                </div>
              </a>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>


      <div class="column column--2of3">
        <div class="userCard">
          <img style="margin: 0rem; z-index: 111; background-color: white;" class="avatar avatar--md dev__avatar" src="{{ profile.imageURL }}" alt="Profile_logo"/>
          <a href="{% url 'Manager_leave_requests' user.id %}" style="width: -webkit-fill-available;">
            <div class="userCard__text">
              <p style="color:black;"><b>{{ profile.user.first_name }} {{ profile.user.last_name }}</b></p>
              <p style="color:black;">{{ profile.user.username }}</p>
            </div>
          </a>
        </div>

        <div class="devInfo">
          <h3 class="devInfo__title">Dostępny urlop: {{ profile.available_leave }} z {% if profile.contract_type == '1' %}26{% else %}13{% endif %} dni</h3>
          <p class="devInfo__about">Urlop na żądanie: {{ profile.on_demand_leave }} z 4 dni</p>
        </div>   
        
        <div class="devInfo">
          <h3 class="devInfo__title">Dodatkowe urlopy:</h3>
          <p class="devInfo__about">Urlop opiekuńczy: {{ profile.parental_leave }} z 5 dni</p>
          <p class="devInfo__about">Urlop z powodu siły wyższej {{ profile.force_majeure_leave }} z 2 dni</p>
        </div>

        <h3 class="devInfo__title">Wnioski do rozpatrzenia:</h3>
        <div class="request_history">
          {% for request in pending_requests %}
            <div class="card text-center"
              {% if request.status == '1' %}    style="background-color:#FFCF87" 
              {% elif request.status == '2' %}  style="background-color:#57BC84"
              {% else %}                        style="background-color:#FF8787"
              {% endif %}
            >
              <div class="cart__card">
                <p class="cart__p"> Data rozpoczęcia: <b>{{ request.start_date|date:"d.m.Y" }}</b></p>
                <p class="cart__p"> Data zakończenia: <b>{{ request.end_date|date:"d.m.Y" }}</b></p>
                <p class="cart__p"> Typ urlopu: <b>{{ request.get_leave_type_display }}</b></p>
                <div class="cart__buttons">
                  <a href="{% url 'decline_leave_request' request.request_id %}" class="request__decline">X</a>
                  <a href="{% url 'accept_leave_request' request.request_id %}" class="request__accept">V</a>
                </div>
              </div>
            </div>
          {% empty%}
            <h3 class="devInfo__title">Brak wniosków...</h3>
          {% endfor %}
        </div>

        <h3 class="devInfo__title">Historia wniosków pracownika:</h3>
        <div class="request_history">
          {% for request in requests_history %}
            <div class="card text-center"
              {% if request.status == '1' %}    style="background-color:#FFCF87" 
              {% elif request.status == '2' %}  style="background-color:#57BC84"
              {% else %}                        style="background-color:#FF8787"
              {% endif %}
            >
              <div class="cart__card">
                <p class="cart__p"> Data rozpoczęcia: <b>{{ request.start_date|date:"d.m.Y" }}</b></p>
                <p class="cart__p"> Data zakończenia: <b>{{ request.end_date|date:"d.m.Y" }}</b></p>
                <p class="cart__p"> Typ urlopu: <b>{{ request.get_leave_type_display }}</b></p>
                <p class="cart__p"> Status: <b>{{ request.get_status_display }}</b></p>
              </div>
            </div>
          {% empty%}
            <h3 class="devInfo__title">Brak wniosków...</h3>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</main>


<script>
  document.addEventListener("DOMContentLoaded", function() {
    const searchBox = document.getElementById('search-box');
    searchBox.addEventListener('keyup', function(e) {
      const searchValue = e.target.value;
  
      // Wysyłanie zapytania AJAX przy każdej zmianie w polu wyszukiwania
      fetch(`/search-users/?query=${searchValue}`)
        .then(response => response.json())
        .then(data => {
          console.log(data);
          // Aktualizacja interfejsu użytkownika z otrzymanymi danymi
          updateUI(data);
        });
    });
  
    function updateUI(users) {
      const container = document.querySelector('.card__body');
      container.innerHTML = ''; 
    
      users.forEach(user => {
        const userCard = document.createElement('div');
        userCard.className = 'userCard';
        userCard.innerHTML = `
          <img style="margin: 0rem; z-index: 111; background-color: white;" class="avatar avatar--md dev__avatar" src="${user.imageURL}" alt="Profile_logo"/>
          <a href="/Manager_leave_requests/${user.id}/" style="width: -webkit-fill-available;">
            <div style="background-color:${user.has_request ? '#FFCF87' : 'inherit'};" class="userCard__text">
              <p style="color:black;"><b>${user.first_name} ${user.last_name}</b></p>
              <p style="color:black;">${user.username}</p>
            </div>
          </a>
        `;
        container.appendChild(userCard);
      });
    }
  });
  </script>
{% endblock %}

Leave_requests/templates/Leave_requests/user_leave_requests.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="settingsPage profile my-xl">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <img class="avatar avatar--xl dev__avatar" src="{{profile.imageURL}}" alt="Profile_logo"/>
            <h2 class="dev__username">{{user.first_name }} {{user.last_name}}</h2>

            <p class="dev__location"><b>Numer pracownika:</b></p>
            <p class="dev__location">{{ user.username }}</p>

            <p class="dev__location"><b>Adres e-mail:</b></p>
            <p class="dev__location">{{ user.email }}</p>

            <p class="dev__location"><b>Adres korespondencji:</b></p>
            <p class="dev__location">{{ profile.city }}, ul. {{ profile.street }} {{ profile.home_number }}</p>

            <p class="dev__location"><b>Kod pocztowy:</b></p>
            <p class="dev__location">{{ profile.postal_code }}</p>

            <p class="dev__location"><b>Numer telefonu:</b></p>
            <p class="dev__location">{{profile.phone_number}}</p>

            <a class="tag tag--pill tag--main settings__btn tag--lg" href="{% url 'edit_account' %}">Edytuj profil</a>
          </div>
        </div>
      </div>


      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">Dostępny urlop: {{ profile.available_leave }} z {% if profile.contract_type == '1' %}26{% else %}13{% endif %} dni</h3>
          <p class="devInfo__about">Urlop na żądanie: {{ profile.on_demand_leave }} z 4 dni</p>
        </div>   
        
        <div class="devInfo">
          <h3 class="devInfo__title">Dodatkowe urlopy:</h3>
          <p class="devInfo__about">Urlop opiekuńczy: {{ profile.parental_leave }} z 5 dni</p>
          <p class="devInfo__about">Urlop z powodu siły wyższej {{ profile.force_majeure_leave }} z 2 dni</p>
        </div>

        <div class="devInfo">
          <h3 class="devInfo__title">Złóż wniosek urlopowy:</h3>
        </div>
        
        <form method="post">
          {% csrf_token %}
          {% for field in form %}
            <p class="leave_request_p">
              <label for="{{ field.id_for_label }}" class="form__label" style="width: 30rem;">{{ field.label }}</label>
              {{ field }}
              {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
              {% endif %}
              {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ error }}
                </div>
              {% endfor %}
            </p>
          {% endfor %}
          <div style="display: flex; justify-content: flex-end;">
            <button type="submit" class="btn btn--main">Wyślij wniosek</button>
          </div>
        </form>
      
        <h3 class="devInfo__title">Historia twoich wniosków:</h3>
        <div class="request_history">
          {% for request in requests_history %}
            <div class="card text-center"
              {% if request.status == '1' %}    style="background-color:#FFCF87" 
              {% elif request.status == '2' %}  style="background-color:#57BC84"
              {% else %}                        style="background-color:#FF8787"
              {% endif %}
            >
              <div class="cart__card">
                <p class="cart__p"> Data rozpoczęcia: <b>{{ request.start_date|date:"d.m.Y" }}</b></p>
                <p class="cart__p"> Data zakończenia: <b>{{ request.end_date|date:"d.m.Y" }}</b></p>
                <p class="cart__p"> Typ urlopu: <b>{{ request.get_leave_type_display }}</b></p>
                <p class="cart__p"> Status: <b>{{ request.get_status_display }}</b></p>
              </div>
            </div>
          {% empty%}
            <h3 class="devInfo__title">Brak wniosków...</h3>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock %}